typography_spectrum: 0.808739583240822
color:
  brandStrength: 0.4589592032134533
  lightness: 0.1605392498895526
  saturation: 0.6213604295626283
  rhythmicContrast: 0.041449025040492415
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.13671751599758863
author:
  name: Joshua Graveline
  email: joshua.stayfit@gmail.com
name: Earthbus
navigation:
  - name: EarthBus' Facebook Page
    url: 'https://www.facebook.com/earthbus/'
    type: external
title: EarthBus
description: One Mans Sustainable Cure for Wanderlust
